language: ruby
cache: bundler
bundler_args: --without development

# if DEPLOY is set skip test prepare
before_script: 'test "$DEPLOY" = "" && bin/rake refinery:testing:dummy_app || echo "skipping dummy app"'

# if DEPLOY is set skip test run
script:
  - 'test "$DEPLOY" = "true" && echo "deploying" || bin/rspec $EXTENSION/spec'
rvm:
  - 2.2
matrix:
  include:
    - rvm: 2.2
      env: DEPLOY=true
sudo: false

# deploy edge demo only for non-PR master commit
after_success:
  - 'test "$TRAVIS_BRANCH" = master && test "$TRAVIS_PULL_REQUEST" = false && bash ci/deploy-edge.sh'
addons:
  ssh_known_hosts:
  - github.com
  - dokku.refinerycms.com

